'use client';
import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { Sparkles, ArrowRight, Play, Edit } from 'lucide-react';
import TopBar from '@/components/layout/TopBar';
import { useWorkflowStore } from '@/store/workflows';
import type { Workflow } from '@/lib/types';

const DEMO_SHORTCUTS: Record<string, Partial<Workflow>> = {
  fastapi: {
    name: 'FastAPI Service with Postgres + CI/CD',
    description: 'Generated by Architect: FastAPI service with PostgreSQL on AWS, CI/CD pipeline, and Slack notification.',
    nodes: [
      { id: 'n1', type: 'create_repo', position: { x: 50, y: 150 }, data: { label: 'Create GitHub Repo', type: 'create_repo', icon: 'Github', status: 'idle' } },
      { id: 'n2', type: 'setup_cicd', position: { x: 280, y: 150 }, data: { label: 'Setup CI/CD', type: 'setup_cicd', icon: 'GitBranch', status: 'idle' } },
      { id: 'n3', type: 'provision_resource', position: { x: 510, y: 80 }, data: { label: 'Provision RDS (Postgres)', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n4', type: 'provision_resource', position: { x: 510, y: 220 }, data: { label: 'Provision EC2 (FastAPI)', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n5', type: 'register_catalog', position: { x: 740, y: 150 }, data: { label: 'Register in Catalog', type: 'register_catalog', icon: 'BookOpen', status: 'idle' } },
      { id: 'n6', type: 'notify_slack', position: { x: 970, y: 150 }, data: { label: 'Notify #engineering', type: 'notify_slack', icon: 'MessageSquare', status: 'idle' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n2', target: 'n4' },
      { id: 'e4', source: 'n3', target: 'n5' },
      { id: 'e5', source: 'n4', target: 'n5' },
      { id: 'e6', source: 'n5', target: 'n6' },
    ],
    explanation: "I've set up a complete FastAPI service stack: a GitHub repo with GitHub Actions CI/CD, a Postgres RDS instance and EC2 for the API on AWS, registered everything in your catalog, and configured a Slack notification to #engineering when it's live.",
  },
  onboarding: {
    name: 'Backend Developer Onboarding',
    description: 'Generated by Architect: Onboard a new backend developer with full access and dev environment.',
    nodes: [
      { id: 'n1', type: 'add_access', position: { x: 50, y: 150 }, data: { label: 'Add GitHub Access', type: 'add_access', icon: 'UserPlus', status: 'idle' } },
      { id: 'n2', type: 'add_access', position: { x: 50, y: 280 }, data: { label: 'Add AWS Access', type: 'add_access', icon: 'UserPlus', status: 'idle' } },
      { id: 'n3', type: 'provision_resource', position: { x: 300, y: 150 }, data: { label: 'Provision Dev Environment', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n4', type: 'register_catalog', position: { x: 530, y: 150 }, data: { label: 'Register Team Member', type: 'register_catalog', icon: 'BookOpen', status: 'idle' } },
      { id: 'n5', type: 'notify_slack', position: { x: 760, y: 150 }, data: { label: 'Welcome to #general', type: 'notify_slack', icon: 'MessageSquare', status: 'idle' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n3' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
      { id: 'e4', source: 'n4', target: 'n5' },
    ],
    explanation: "I've configured a complete onboarding flow: GitHub and AWS access provisioning in parallel, a dev environment spun up automatically, the new member registered in the service catalog, and a welcome message posted to #general.",
  },
  staging: {
    name: 'Staging Environment — payments-service',
    description: 'Generated by Architect: Spin up a staging environment for payments-service with approval gate.',
    nodes: [
      { id: 'n1', type: 'approval_gate', position: { x: 50, y: 150 }, data: { label: 'Approval Gate (CTO)', type: 'approval_gate', icon: 'CheckSquare', status: 'idle' } },
      { id: 'n2', type: 'provision_resource', position: { x: 300, y: 80 }, data: { label: 'Clone Production DB', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n3', type: 'provision_resource', position: { x: 300, y: 220 }, data: { label: 'Provision Staging EC2', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n4', type: 'register_catalog', position: { x: 550, y: 150 }, data: { label: 'Register Staging Env', type: 'register_catalog', icon: 'BookOpen', status: 'idle' } },
      { id: 'n5', type: 'notify_slack', position: { x: 780, y: 150 }, data: { label: 'Notify #deployments', type: 'notify_slack', icon: 'MessageSquare', status: 'idle' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n1', target: 'n3' },
      { id: 'e3', source: 'n2', target: 'n4' },
      { id: 'e4', source: 'n3', target: 'n4' },
      { id: 'e5', source: 'n4', target: 'n5' },
    ],
    explanation: "I've set up a staging environment workflow for payments-service: an approval gate (requires CTO sign-off), parallel provisioning of a cloned production DB and a new EC2 instance, registration in the catalog as 'staging', and a Slack notification to #deployments.",
  },
};

function detectShortcut(input: string): string | null {
  const lower = input.toLowerCase();
  if (lower.includes('fastapi') || lower.includes('postgres') || lower.includes('fast api')) return 'fastapi';
  if (lower.includes('onboard') || lower.includes('developer') || lower.includes('backend engineer')) return 'onboarding';
  if (lower.includes('staging') || lower.includes('environment') || lower.includes('payments')) return 'staging';
  return null;
}

const EXAMPLE_PROMPTS = [
  'I need a FastAPI service with a Postgres database on AWS, CI/CD, and a Slack notification',
  'Set up onboarding for a new backend developer joining our team',
  'Create a staging environment for our payments service',
];

export default function ArchitectPage() {
  const router = useRouter();
  const { addWorkflow } = useWorkflowStore();
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<(Partial<Workflow> & { explanation?: string }) | null>(null);
  const [generatedId, setGeneratedId] = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setResult(null);

    await new Promise((r) => setTimeout(r, 1800));

    const shortcut = detectShortcut(prompt);
    const template = shortcut ? DEMO_SHORTCUTS[shortcut] : DEMO_SHORTCUTS.fastapi;

    const id = `generated-${Date.now()}`;
    const workflow: Workflow = {
      id,
      name: template.name ?? 'Generated Workflow',
      description: template.description ?? prompt,
      icon: 'Sparkles',
      nodes: template.nodes ?? [],
      edges: template.edges ?? [],
      runCount: 0,
      lastRunAt: 'never',
      createdAt: new Date().toISOString(),
      isTemplate: false,
    };

    addWorkflow(workflow);
    setGeneratedId(id);
    setResult({ ...template });
    setLoading(false);
  }, [prompt, addWorkflow]);

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
      <TopBar title="The Architect" subtitle="Describe what you need in plain English" />

      <main style={{
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '48px 24px',
        gap: 32,
      }}>
        {/* Hero */}
        <div style={{ textAlign: 'center', maxWidth: 600 }}>
          <div style={{
            width: 52,
            height: 52,
            borderRadius: 14,
            background: 'var(--brand-glow)',
            border: '1px solid var(--border-brand)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 16px',
          }}>
            <Sparkles size={24} color="var(--brand-400)" />
          </div>
          <h1 style={{
            fontFamily: 'var(--font-sora)',
            fontSize: 28,
            fontWeight: 700,
            color: 'var(--text-primary)',
            marginBottom: 10,
          }}>
            Describe your workflow
          </h1>
          <p style={{ fontSize: 15, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            Tell the Architect what you need. It will map your description to the right steps, configure them, and build a ready-to-run workflow.
          </p>
        </div>

        {/* Input */}
        <div style={{ width: '100%', maxWidth: 680 }}>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => {
              if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') handleGenerate();
            }}
            placeholder="I need a FastAPI service with a Postgres database on AWS, a CI/CD pipeline, and a Slack notification when deployed..."
            rows={4}
            style={{
              width: '100%',
              padding: '16px',
              borderRadius: 12,
              background: 'var(--bg-surface)',
              border: '1px solid var(--border-default)',
              color: 'var(--text-primary)',
              fontSize: 15,
              lineHeight: 1.6,
              outline: 'none',
              resize: 'vertical',
              transition: 'border-color 150ms',
              fontFamily: 'var(--font-dm-sans)',
            }}
            onFocus={(e) => { e.currentTarget.style.borderColor = 'var(--brand-500)'; }}
            onBlur={(e) => { e.currentTarget.style.borderColor = 'var(--border-default)'; }}
          />

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 }}>
            <p style={{ fontSize: 12, color: 'var(--text-muted)' }}>
              <kbd style={{ padding: '2px 6px', borderRadius: 4, background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)', fontSize: 11 }}>⌘ Enter</kbd>
              {' '}to generate
            </p>
            <button
              onClick={handleGenerate}
              disabled={!prompt.trim() || loading}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                padding: '10px 20px',
                borderRadius: 8,
                background: (!prompt.trim() || loading) ? 'var(--bg-elevated)' : 'var(--brand-500)',
                color: (!prompt.trim() || loading) ? 'var(--text-muted)' : 'white',
                border: 'none',
                cursor: (!prompt.trim() || loading) ? 'not-allowed' : 'pointer',
                fontSize: 14,
                fontWeight: 500,
                transition: 'background 150ms',
              }}
            >
              {loading ? (
                <>
                  <span style={{ animation: 'spin 1s linear infinite', display: 'inline-block' }}>◌</span>
                  Architect is thinking...
                </>
              ) : (
                <>Generate Workflow <ArrowRight size={15} /></>
              )}
            </button>
          </div>

          {/* Loading animation */}
          {loading && (
            <div style={{
              marginTop: 16,
              padding: '16px',
              borderRadius: 10,
              background: 'var(--bg-surface)',
              border: '1px solid var(--border-brand)',
              display: 'flex',
              alignItems: 'center',
              gap: 12,
            }}>
              <div style={{
                width: 32,
                height: 32,
                borderRadius: 8,
                background: 'linear-gradient(135deg, var(--brand-500), #8B5CF6)',
                backgroundSize: '200% 200%',
                animation: 'gradientShift 2s ease infinite, fadeIn 200ms ease',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}>
                <Sparkles size={16} color="white" />
              </div>
              <div>
                <div style={{ fontSize: 14, fontWeight: 500, color: 'var(--text-primary)' }}>Architect is thinking...</div>
                <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 2 }}>Mapping your description to workflow steps</div>
              </div>
            </div>
          )}
        </div>

        {/* Example prompts */}
        {!result && !loading && (
          <div style={{ width: '100%', maxWidth: 680 }}>
            <p style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 10 }}>Try an example:</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {EXAMPLE_PROMPTS.map((ex) => (
                <button
                  key={ex}
                  onClick={() => setPrompt(ex)}
                  style={{
                    textAlign: 'left',
                    padding: '10px 14px',
                    borderRadius: 8,
                    background: 'var(--bg-surface)',
                    border: '1px solid var(--border-default)',
                    color: 'var(--text-secondary)',
                    fontSize: 13,
                    cursor: 'pointer',
                    transition: 'all 150ms',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.borderColor = 'var(--border-brand)';
                    e.currentTarget.style.color = 'var(--text-primary)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.borderColor = 'var(--border-default)';
                    e.currentTarget.style.color = 'var(--text-secondary)';
                  }}
                >
                  <ArrowRight size={13} color="var(--brand-400)" style={{ flexShrink: 0 }} />
                  {ex}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Result */}
        {result && generatedId && (
          <div style={{
            width: '100%',
            maxWidth: 680,
            animation: 'fadeInUp 300ms ease both',
          }}>
            <div style={{
              background: 'var(--bg-surface)',
              border: '1px solid var(--border-brand)',
              borderRadius: 12,
              overflow: 'hidden',
            }}>
              <div style={{
                padding: '16px 20px',
                borderBottom: '1px solid var(--border-subtle)',
                background: 'var(--brand-glow)',
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                  <Sparkles size={14} color="var(--brand-400)" />
                  <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--brand-400)' }}>Workflow Generated</span>
                </div>
                <h3 style={{ fontFamily: 'var(--font-sora)', fontSize: 16, fontWeight: 600, color: 'var(--text-primary)' }}>
                  {result.name}
                </h3>
              </div>

              <div style={{ padding: '16px 20px' }}>
                {/* Node preview */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 4, flexWrap: 'wrap', marginBottom: 16 }}>
                  {(result.nodes ?? []).map((node, idx) => (
                    <span key={node.id} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                      <span style={{
                        fontSize: 11,
                        color: 'var(--text-secondary)',
                        background: 'var(--bg-elevated)',
                        padding: '4px 10px',
                        borderRadius: 6,
                        border: '1px solid var(--border-default)',
                      }}>
                        {node.data.label}
                      </span>
                      {idx < (result.nodes ?? []).length - 1 && (
                        <span style={{ color: 'var(--brand-400)', fontSize: 14 }}>→</span>
                      )}
                    </span>
                  ))}
                </div>

                {result.explanation && (
                  <div style={{
                    padding: '12px 14px',
                    borderRadius: 8,
                    background: 'var(--bg-elevated)',
                    border: '1px solid var(--border-subtle)',
                    fontSize: 13,
                    color: 'var(--text-secondary)',
                    lineHeight: 1.6,
                    marginBottom: 16,
                  }}>
                    {result.explanation}
                  </div>
                )}

                <div style={{ display: 'flex', gap: 10 }}>
                  <button
                    onClick={() => router.push(`/workflows/${generatedId}`)}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 6,
                      padding: '9px 16px',
                      borderRadius: 8,
                      background: 'transparent',
                      border: '1px solid var(--border-default)',
                      color: 'var(--text-secondary)',
                      fontSize: 13,
                      fontWeight: 500,
                      cursor: 'pointer',
                    }}
                  >
                    <Edit size={13} /> Edit in Builder
                  </button>
                  <button
                    onClick={() => router.push(`/workflows/${generatedId}?run=true`)}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 6,
                      padding: '9px 16px',
                      borderRadius: 8,
                      background: 'var(--brand-500)',
                      border: 'none',
                      color: 'white',
                      fontSize: 13,
                      fontWeight: 500,
                      cursor: 'pointer',
                    }}
                  >
                    <Play size={13} /> Run Now
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
