import type { Service, Workflow, ActivityEvent, Integration, TeamMember } from './types';

export const TEAM_MEMBERS: TeamMember[] = [
  { id: 'tm1', name: 'Ana Rodriguez', email: 'ana@acme.com', role: 'Platform Lead', avatar: 'AR', joinedAt: '2023-01-15' },
  { id: 'tm2', name: 'Marcus Chen', email: 'marcus@acme.com', role: 'Backend Engineer', avatar: 'MC', joinedAt: '2024-05-13' },
  { id: 'tm3', name: 'Jordan Kim', email: 'jordan@acme.com', role: 'Data Engineer', avatar: 'JK', joinedAt: '2023-06-01' },
  { id: 'tm4', name: 'Priya Sharma', email: 'priya@acme.com', role: 'Backend Engineer', avatar: 'PS', joinedAt: '2023-03-20' },
  { id: 'tm5', name: 'Leo Zhang', email: 'leo@acme.com', role: 'Frontend Engineer', avatar: 'LZ', joinedAt: '2023-08-10' },
  { id: 'tm6', name: 'You', email: 'you@acme.com', role: 'CTO', avatar: 'YO', joinedAt: '2022-11-01' },
];

export const SERVICES: Service[] = [
  {
    id: 'payments-service',
    name: 'payments-service',
    description: 'Handles all payment processing via Stripe. Manages subscriptions, one-time charges, and refund workflows.',
    status: 'healthy',
    stack: ['Node.js', 'Stripe', 'PostgreSQL'],
    owner: TEAM_MEMBERS[0],
    repoUrl: 'https://github.com/acme/payments-service',
    docsUrl: '#',
    runbookUrl: '#',
    lastDeployedAt: '2024-05-16T08:00:00Z',
    lastDeployedBy: 'Ana Rodriguez',
    uptime: '99.98%',
    latency: '42ms',
    errorRate: '0.01%',
    dependencies: ['auth-service', 'notification-worker'],
    deployments: [
      { id: 'd1', version: 'v2.4.1', deployedBy: 'Ana Rodriguez', deployedAt: '2h ago', status: 'success', duration: '2m 14s', commit: 'a3f9c12', message: 'Fix retry logic on failed charges' },
      { id: 'd2', version: 'v2.4.0', deployedBy: 'Ana Rodriguez', deployedAt: '3d ago', status: 'success', duration: '1m 58s', commit: 'b7e2d09', message: 'Add webhook signature validation' },
      { id: 'd3', version: 'v2.3.9', deployedBy: 'Priya Sharma', deployedAt: '1w ago', status: 'success', duration: '2m 03s', commit: 'c4a8f11', message: 'Upgrade Stripe SDK to v12' },
    ],
  },
  {
    id: 'auth-service',
    name: 'auth-service',
    description: 'JWT-based authentication and authorization. Handles login, signup, token refresh, and OAuth flows.',
    status: 'healthy',
    stack: ['Python', 'FastAPI', 'PostgreSQL'],
    owner: TEAM_MEMBERS[3],
    repoUrl: 'https://github.com/acme/auth-service',
    lastDeployedAt: '2024-05-14T12:00:00Z',
    lastDeployedBy: 'Priya Sharma',
    uptime: '99.99%',
    latency: '18ms',
    errorRate: '0.00%',
    dependencies: [],
    deployments: [
      { id: 'd4', version: 'v1.9.2', deployedBy: 'Priya Sharma', deployedAt: '2d ago', status: 'success', duration: '1m 42s', commit: 'd2b5e03', message: 'Add MFA support' },
      { id: 'd5', version: 'v1.9.1', deployedBy: 'Priya Sharma', deployedAt: '5d ago', status: 'success', duration: '1m 38s', commit: 'e9c1a07', message: 'Fix token expiry edge case' },
    ],
  },
  {
    id: 'notification-worker',
    name: 'notification-worker',
    description: 'Background job processor for email, SMS, and push notifications. Uses Celery with Redis as broker.',
    status: 'degraded',
    stack: ['Python', 'Redis', 'Celery'],
    owner: TEAM_MEMBERS[1],
    repoUrl: 'https://github.com/acme/notification-worker',
    lastDeployedAt: '2024-05-12T09:30:00Z',
    lastDeployedBy: 'Marcus Chen',
    uptime: '97.2%',
    latency: '320ms',
    errorRate: '2.4%',
    dependencies: ['email-service'],
    deployments: [
      { id: 'd6', version: 'v3.1.0', deployedBy: 'Marcus Chen', deployedAt: '4d ago', status: 'success', duration: '3m 01s', commit: 'f1d4b09', message: 'Migrate to Celery 5.x' },
    ],
  },
  {
    id: 'frontend-web',
    name: 'frontend-web',
    description: 'Main customer-facing web application built with Next.js. Deployed on Vercel with edge rendering.',
    status: 'healthy',
    stack: ['Next.js', 'React', 'Vercel'],
    owner: TEAM_MEMBERS[4],
    repoUrl: 'https://github.com/acme/frontend-web',
    lastDeployedAt: '2024-05-15T16:00:00Z',
    lastDeployedBy: 'You',
    uptime: '99.97%',
    latency: '95ms',
    errorRate: '0.02%',
    dependencies: ['auth-service', 'payments-service'],
    deployments: [
      { id: 'd7', version: 'v5.2.3', deployedBy: 'You', deployedAt: '1d ago', status: 'success', duration: '45s', commit: 'g7h8i01', message: 'New onboarding flow' },
    ],
  },
  {
    id: 'admin-dashboard',
    name: 'admin-dashboard',
    description: 'Internal admin tool for customer support and operations teams. Feature-flagged with Unleash.',
    status: 'healthy',
    stack: ['React', 'PostgreSQL'],
    owner: TEAM_MEMBERS[4],
    repoUrl: 'https://github.com/acme/admin-dashboard',
    lastDeployedAt: '2024-05-10T11:00:00Z',
    lastDeployedBy: 'Leo Zhang',
    uptime: '99.90%',
    latency: '120ms',
    errorRate: '0.05%',
    dependencies: ['auth-service'],
    deployments: [
      { id: 'd8', version: 'v2.0.1', deployedBy: 'Leo Zhang', deployedAt: '6d ago', status: 'success', duration: '1m 12s', commit: 'h3j4k05', message: 'Add bulk user management' },
    ],
  },
  {
    id: 'data-pipeline',
    name: 'data-pipeline',
    description: 'Orchestrates ETL jobs using Apache Airflow. Moves data from production DBs to the analytics warehouse.',
    status: 'deploying',
    stack: ['Python', 'Airflow', 'BigQuery'],
    owner: TEAM_MEMBERS[2],
    repoUrl: 'https://github.com/acme/data-pipeline',
    lastDeployedAt: '2024-05-16T09:45:00Z',
    lastDeployedBy: 'Jordan Kim',
    uptime: '99.50%',
    latency: '—',
    errorRate: '—',
    dependencies: ['analytics-service'],
    deployments: [
      { id: 'd9', version: 'v4.3.0', deployedBy: 'Jordan Kim', deployedAt: 'Now', status: 'in_progress', duration: '—', commit: 'i5l6m07', message: 'Add revenue attribution DAG' },
    ],
  },
  {
    id: 'recommendation-engine',
    name: 'recommendation-engine',
    description: 'ML-powered product recommendation service. Serves personalized recommendations via REST API.',
    status: 'healthy',
    stack: ['Python', 'ML', 'AWS'],
    owner: TEAM_MEMBERS[2],
    repoUrl: 'https://github.com/acme/recommendation-engine',
    lastDeployedAt: '2024-05-08T14:00:00Z',
    lastDeployedBy: 'Jordan Kim',
    uptime: '99.85%',
    latency: '240ms',
    errorRate: '0.1%',
    dependencies: ['data-pipeline'],
    deployments: [
      { id: 'd10', version: 'v1.4.2', deployedBy: 'Jordan Kim', deployedAt: '8d ago', status: 'success', duration: '4m 30s', commit: 'j9n0o08', message: 'Retrain model with Q1 data' },
    ],
  },
  {
    id: 'file-storage-service',
    name: 'file-storage-service',
    description: 'Handles file uploads, downloads, and transformations. Stores files in S3 with pre-signed URLs.',
    status: 'healthy',
    stack: ['Go', 'S3', 'AWS'],
    owner: TEAM_MEMBERS[0],
    repoUrl: 'https://github.com/acme/file-storage-service',
    lastDeployedAt: '2024-05-05T10:00:00Z',
    lastDeployedBy: 'Ana Rodriguez',
    uptime: '99.99%',
    latency: '28ms',
    errorRate: '0.00%',
    dependencies: [],
    deployments: [
      { id: 'd11', version: 'v2.1.0', deployedBy: 'Ana Rodriguez', deployedAt: '11d ago', status: 'success', duration: '52s', commit: 'k1p2q09', message: 'Add multipart upload support' },
    ],
  },
  {
    id: 'analytics-service',
    name: 'analytics-service',
    description: 'Aggregates product analytics events and serves dashboards. Uses BigQuery for OLAP queries.',
    status: 'healthy',
    stack: ['Python', 'BigQuery', 'GCP'],
    owner: TEAM_MEMBERS[2],
    repoUrl: 'https://github.com/acme/analytics-service',
    lastDeployedAt: '2024-05-13T15:00:00Z',
    lastDeployedBy: 'Jordan Kim',
    uptime: '99.92%',
    latency: '380ms',
    errorRate: '0.08%',
    dependencies: ['data-pipeline'],
    deployments: [
      { id: 'd12', version: 'v3.0.4', deployedBy: 'Jordan Kim', deployedAt: '3d ago', status: 'success', duration: '2m 15s', commit: 'l3r4s10', message: 'Add funnel analysis endpoints' },
    ],
  },
  {
    id: 'email-service',
    name: 'email-service',
    description: 'Transactional email delivery using SendGrid. Handles templating, tracking, and unsubscribes.',
    status: 'healthy',
    stack: ['Node.js', 'SendGrid'],
    owner: TEAM_MEMBERS[1],
    repoUrl: 'https://github.com/acme/email-service',
    lastDeployedAt: '2024-05-11T09:00:00Z',
    lastDeployedBy: 'Marcus Chen',
    uptime: '99.96%',
    latency: '65ms',
    errorRate: '0.03%',
    dependencies: [],
    deployments: [
      { id: 'd13', version: 'v1.6.1', deployedBy: 'Marcus Chen', deployedAt: '5d ago', status: 'success', duration: '1m 05s', commit: 'm5t6u11', message: 'Add unsubscribe webhook handler' },
    ],
  },
];

export const WORKFLOW_TEMPLATES: Workflow[] = [
  {
    id: 'new-service-setup',
    name: 'New Service Setup',
    description: 'Create a GitHub repo, set up CI/CD, provision cloud resources, register in catalog, and notify Slack.',
    icon: 'Rocket',
    runCount: 12,
    lastRunAt: '3h ago',
    createdAt: '2024-03-01',
    isTemplate: true,
    nodes: [
      { id: 'n1', type: 'create_repo', position: { x: 50, y: 150 }, data: { label: 'Create GitHub Repo', type: 'create_repo', icon: 'Github', status: 'idle' } },
      { id: 'n2', type: 'setup_cicd', position: { x: 280, y: 150 }, data: { label: 'Setup CI/CD', type: 'setup_cicd', icon: 'GitBranch', status: 'idle' } },
      { id: 'n3', type: 'provision_resource', position: { x: 510, y: 150 }, data: { label: 'Provision Cloud Resource', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n4', type: 'register_catalog', position: { x: 740, y: 150 }, data: { label: 'Register in Catalog', type: 'register_catalog', icon: 'BookOpen', status: 'idle' } },
      { id: 'n5', type: 'notify_slack', position: { x: 970, y: 150 }, data: { label: 'Notify Slack', type: 'notify_slack', icon: 'MessageSquare', status: 'idle' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
      { id: 'e4', source: 'n4', target: 'n5' },
    ],
  },
  {
    id: 'developer-onboarding',
    name: 'Developer Onboarding',
    description: 'Add team member access, provision dev environment, register in catalog, and welcome to Slack.',
    icon: 'Users',
    runCount: 6,
    lastRunAt: '1d ago',
    createdAt: '2024-03-05',
    isTemplate: true,
    nodes: [
      { id: 'n1', type: 'add_access', position: { x: 50, y: 150 }, data: { label: 'Add Team Member Access', type: 'add_access', icon: 'UserPlus', status: 'idle' } },
      { id: 'n2', type: 'provision_resource', position: { x: 300, y: 150 }, data: { label: 'Provision Dev Environment', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n3', type: 'register_catalog', position: { x: 550, y: 150 }, data: { label: 'Register in Catalog', type: 'register_catalog', icon: 'BookOpen', status: 'idle' } },
      { id: 'n4', type: 'notify_slack', position: { x: 800, y: 150 }, data: { label: 'Notify Slack', type: 'notify_slack', icon: 'MessageSquare', status: 'idle' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
    ],
  },
  {
    id: 'spin-up-environment',
    name: 'Spin Up Environment',
    description: 'Request approval, provision cloud resources, and notify Slack when the environment is ready.',
    icon: 'Cloud',
    runCount: 8,
    lastRunAt: '3d ago',
    createdAt: '2024-03-10',
    isTemplate: true,
    nodes: [
      { id: 'n1', type: 'approval_gate', position: { x: 50, y: 150 }, data: { label: 'Approval Gate', type: 'approval_gate', icon: 'CheckSquare', status: 'idle' } },
      { id: 'n2', type: 'provision_resource', position: { x: 300, y: 150 }, data: { label: 'Provision Cloud Resource', type: 'provision_resource', icon: 'Cloud', status: 'idle' } },
      { id: 'n3', type: 'notify_slack', position: { x: 550, y: 150 }, data: { label: 'Notify Slack', type: 'notify_slack', icon: 'MessageSquare', status: 'idle' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
    ],
  },
];

export const ACTIVITY_FEED: ActivityEvent[] = [
  { id: 'a1', emoji: '', message: 'payments-service deployed by Ana Rodriguez', timestamp: '2024-05-16T08:00:00Z', relativeTime: '2h ago', type: 'deploy' },
  { id: 'a2', emoji: '', message: 'New Service Setup workflow completed for "auth-v2"', timestamp: '2024-05-16T07:00:00Z', relativeTime: '3h ago', type: 'workflow' },
  { id: 'a3', emoji: '', message: 'Marcus Chen joined the team', timestamp: '2024-05-16T05:00:00Z', relativeTime: '5h ago', type: 'team' },
  { id: 'a4', emoji: '', message: 'notification-worker degraded — high memory usage', timestamp: '2024-05-16T04:00:00Z', relativeTime: '6h ago', type: 'alert' },
  { id: 'a5', emoji: '', message: 'frontend-web deployed by You', timestamp: '2024-05-15T10:00:00Z', relativeTime: '1d ago', type: 'deploy' },
  { id: 'a6', emoji: '', message: 'Developer Onboarding completed for Marcus Chen', timestamp: '2024-05-15T09:00:00Z', relativeTime: '1d ago', type: 'workflow' },
  { id: 'a7', emoji: '', message: 'AWS integration connected', timestamp: '2024-05-14T14:00:00Z', relativeTime: '2d ago', type: 'integration' },
  { id: 'a8', emoji: '', message: 'analytics-service registered in catalog', timestamp: '2024-05-14T11:00:00Z', relativeTime: '2d ago', type: 'catalog' },
  { id: 'a9', emoji: '', message: 'data-pipeline deployed by Jordan Kim', timestamp: '2024-05-13T16:00:00Z', relativeTime: '3d ago', type: 'deploy' },
  { id: 'a10', emoji: '', message: 'Spin Up Environment completed for staging-v2', timestamp: '2024-05-13T10:00:00Z', relativeTime: '3d ago', type: 'workflow' },
];

export const INTEGRATIONS: Integration[] = [
  { id: 'github', name: 'GitHub', description: 'Connect your repos, automate workflows, and track deployments.', logo: 'Github', status: 'connected', detail: 'acme-org (24 repos)' },
  { id: 'aws', name: 'AWS', description: 'Provision EC2, RDS, S3, Lambda, and more from Shipyard workflows.', logo: 'Cloud', status: 'connected', detail: 'us-east-1' },
  { id: 'slack', name: 'Slack', description: 'Send notifications to your team channels when workflows complete.', logo: 'MessageSquare', status: 'connected', detail: '#engineering, #deployments' },
  { id: 'gcp', name: 'Google Cloud', description: 'Provision GKE, Cloud Run, Cloud SQL, and GCS resources.', logo: 'Cloud', status: 'disconnected' },
  { id: 'vercel', name: 'Vercel', description: 'Deploy frontend services and manage preview environments.', logo: 'Triangle', status: 'disconnected' },
  { id: 'pagerduty', name: 'PagerDuty', description: 'Route alerts and trigger incident response workflows.', logo: 'Bell', status: 'disconnected' },
  { id: 'datadog', name: 'Datadog', description: 'Pull service health metrics into your catalog automatically.', logo: 'Activity', status: 'disconnected' },
  { id: 'linear', name: 'Linear', description: 'Link issues to deployments and track work in context.', logo: 'Layers', status: 'disconnected' },
];

export const EXECUTION_LOGS = [
  { time: '10:42:01', icon: '>', message: 'Starting workflow: New Service Setup', type: 'info' },
  { time: '10:42:01', icon: '+', message: 'Creating GitHub repository: payments-v2', type: 'success' },
  { time: '10:42:03', icon: '+', message: 'Repository created: github.com/acme/payments-v2', type: 'success' },
  { time: '10:42:03', icon: '>', message: 'Setting up CI/CD pipeline...', type: 'info' },
  { time: '10:42:05', icon: '+', message: 'GitHub Actions workflow configured', type: 'success' },
  { time: '10:42:05', icon: '>', message: 'Provisioning AWS resources...', type: 'info' },
  { time: '10:42:08', icon: '+', message: 'RDS instance created: payments-v2-db', type: 'success' },
  { time: '10:42:08', icon: '>', message: 'Registering service in catalog...', type: 'info' },
  { time: '10:42:09', icon: '+', message: 'Service registered: payments-v2', type: 'success' },
  { time: '10:42:09', icon: '>', message: 'Sending Slack notification...', type: 'info' },
  { time: '10:42:10', icon: '+', message: 'Message sent to #engineering', type: 'success' },
  { time: '10:42:10', icon: '*', message: 'Workflow complete in 9s', type: 'complete' },
];
